画像をバリデーションするためのクラス群を作成
SunriseDigital/cs-sdx pull request #110
Opened 2017-03-02 10:12 UTC by matsukawa1

## 関連するPR/Issue

## Page

## チェック

## TODO

2017-03-03 06:56 UTC, matsukawa1 commented
## 実装イメージ
```csharp
var validators = new Sdx.Validation.Image.ValidatorSet();

validators.Add(new Sdx.Validation.Image.MaxSize(width: 200, height: 100));
validators.Add(new Sdx.Validation.Image.MinSize(width: 50, height: 50));
validators.Add(new Sdx.Validation.Image.Type(Type.Jpeg, Type.Png, Type.AGif));
validators.Add(new Sdx.Validation.Image.Capacity(1024 * 10));

if(validators.IsValid(bitmap))
{
  //正しかった
}
```

2017-03-03 09:02 UTC, gomo commented
## 容量が取れない問題

```c#
var image = new Sdx.Image(postedFile.InputStream);
validators.Add(new Sdx.Validation.Image.MaxSize(width: 200, height: 100));
validators.Add(new Sdx.Validation.Image.MinSize(width: 50, height: 50));
validators.Add(new Sdx.Validation.Image.Type(Type.Jpeg, Type.Png, Type.AGif));
validators.Add(new Sdx.Validation.Image.Capacity(1024 * 10));

if(validators.IsValid(image))
{
  //正しかった
}

Common.AwsS3.Nantoka.Save(image.Stream);
```

2017-03-03 09:47 UTC, matsukawa1 commented
ストリームは遅延で呼ぶ。

サイズやタイプ(jpegなど)を取得するときはstreamは不要。

2017-03-03 10:32 UTC, matsukawa1 commented
Oｈ。。。

System.Drawing.Imageは抽象クラスだからインスタンス化できない。。。orz

2017-03-09 09:19 UTC, matsukawa1 commented on Sdx/Image.cs
> +      }
try~catchの詳細調査。

2017-03-10 01:50 UTC, matsukawa1 commented on Sdx/Validation/Image/Type.cs
> +    public List<string> FormatList = new List<string>();
FormatListはtypeListに変えます。
古い記述の変更のし忘れのようです。

2017-03-10 01:53 UTC, matsukawa1 commented on Sdx/Validation/Image/Capacity.cs
> +    public const string ErrorOverCapacityLImit = "ErrorOverCapacityLImit";
ErrorOverCapacityLImit 

LImitになってますね。。。修正しておきます。

2017-03-10 03:32 UTC, gomo requested changes

2017-03-10 03:32 UTC, gomo commented on Sdx/Image.cs
> +    string type = null; //ファイルの種類
ファイルの種類はテキストじゃないほうがいいですね。enumで管理がベストだと思うけど難しい？ちなみに.Netに汎用的なファイル形式（mimetype？）の定数群とかenumってないの？あったらそっちがベストですかね？

😇

2017-03-10 03:32 UTC, gomo commented on Sdx/Image.cs
> +      }
直さなくていいけどこれって

```c#
      get{
        if(this.bitmap == null){
            this.bitmap = new Bitmap(this.stream);
        }

        return this.bitmap;
      }
```

の方がコードも短くて直感的じゃない？returnが二つあるのも一瞬戸惑うし、`(this.bitmap != null)`というのが否定の比較なのでわかりづらいです。

好みの問題かね？前も松川くんにこの指摘した気がするけど、こっちの方が好き？

処理を日本語の文章にしてみるとこんな感じ

前者
* ビットマップがnullじゃなかったらビットマップを返す。
* ビットマップを生成する。
* ビットマップを返す。

後者
* ビットマップがnullだったら生成する。
* ビットマップを返す。

どっちがわかりやすい？

2017-03-10 03:32 UTC, gomo commented on Sdx/Image.cs
> +    }
こういうプロパティはthis.typeを持つ必要ないですね。

```c#
private string Type {get; set;}
```

でOKです。てかそもそもprivateならプロパティーにしなくてもOKな気もするけど。いや、これそもそもprivateでいいのか？

とりあえずprivateにしておいて必要になったら公開するというのは正しいやり方だけど・・・とはいえ、確実に必要になりそうなプロパティーではあるね。

まあ、privateのままにしておきましょうか。とりあえずメンバー変数はいらないかな。

😇

2017-03-10 03:32 UTC, gomo commented on Sdx/Image.cs
> +  }
えーと、このメソッドはいらないかな。Typeの中で遅延チェックしてやればいいのでは？

😇

2017-03-10 03:32 UTC, gomo commented on Sdx/Image.cs
> +          return string.Empty;
これだと、不明だった場合、何度もチェックが走るね。不明だったら不明だったでその値をキャッシュしないとダメですね。

😇

2017-03-10 03:32 UTC, gomo commented on Sdx/Image.cs
> +      catch
この例外は握りつぶして大丈夫？基本例外の握りつぶしはご法度だと思います。しかも全ての例外を握りつぶすのはさらにまずいと思う。
握りつぶす理由があったら相談してください。検討します。

😇

2017-03-10 03:32 UTC, gomo commented on Sdx/Validation/Base/Validator.cs
> +}
あ、Baseは名前空間じゃなくてクラス名ですね。

これは全部のクラスの親ですよね？だったら`Sdx.Validation.Base`かな。

あとやっぱり基底クラスなのでIsValidを持ってないのは気持ち悪いね。この話ってでたっけ？インターフェース的に何の意味もない基底クラスってことになっちゃう。

これ、IsValid(object)を抽象メソッドかテンプレートメソッドかで持たせるのはむずかしい？


😇

2017-03-10 03:32 UTC, gomo commented on Sdx/Validation/Image/Type.cs
> +    public const string gif = "GIF";
この辺もSdx.Image.Type.Jpegとかenumを利用することになるのかな？

2017-03-10 03:32 UTC, gomo commented on Sdx/Validation/Image/ValidatorSet.cs
> +}
このクラスは`Sdx.Validation.ValidatorSet`にして、Image以外も使えるようにすると難しい？

https://github.com/SunriseDigital/cs-sdx/pull/110/files#r105322895
この辺の話と関連して来そうだけど、`Sdx.Validation.IValidator`を`IsValid(object)` `IsValid(object[])`  `Errors`の三つを定義しておいて、FormElementにAddするのもValidatorSetにAddするのもIValidatorにしておくのが綺麗な気がしたけど難しいかな？

なんなら、ValidatorSetにもIValidatorをImplementしておけばひとかたまりで使うバリデータを生成できるようにしておいてFormにセットもできるね。

話出たと思うけどZend FrameWorkのパターンですね。

こういうのって、一度最低限の実装でやってみて、正しいアプローチかどうかを判断しないといけないので色々時間かかるんですよね。休みの件とかものあるのであれですけど、Sdxなんでやっつけないで検討して見たいです。

タイミングによっては引き継ぐかもしれないですけど、Ajax使わない管理画面の実装終わったらこっちを試してもらえますか？

手をつけるときは相談してください。

😇

2017-03-10 10:41 UTC, matsukawa1 commented on Sdx/Image.cs
> +      }
後者ですね。

悪い癖が付いているみたいです。。。

修正します！

2017-03-13 07:59 UTC, matsukawa1 commented on Sdx/Validation/Image/Capacity.cs
> +    public const string ErrorOverCapacityLImit = "ErrorOverCapacityLImit";
修正完了

2017-03-13 08:02 UTC, matsukawa1 commented on Sdx/Image.cs
> +      }
修正完了

2017-03-13 08:23 UTC, matsukawa1 commented on Sdx/Image.cs
> +    }
修正完了
Typeプロパティでデータを取得できるようにしました。

2017-03-13 08:23 UTC, matsukawa1 commented on Sdx/Image.cs
> +  }
修正完了
Typeプロパティでデータを取得できるようにしました。

2017-03-13 08:23 UTC, matsukawa1 commented on Sdx/Image.cs
> +      catch
修正完了

2017-03-13 08:23 UTC, matsukawa1 commented on Sdx/Image.cs
> +          return string.Empty;
修正完了

2017-03-13 08:24 UTC, matsukawa1 commented on Sdx/Image.cs
> +      }
修正完了

2017-03-14 06:17 UTC, matsukawa1 commented on Sdx/Image.cs
> +    string type = null; //ファイルの種類
enumで実装するように修正。完了。

2017-03-14 06:18 UTC, matsukawa1 commented on Sdx/Validation/Image/Type.cs
> +    public const string gif = "GIF";
修正完了

2017-03-14 07:57 UTC, matsukawa1 commented on Sdx/Validation/Base/Validator.cs
> +}
Sdx.Validation.Baseクラスに置き換える作業完了。

>これ、IsValid(object)を抽象メソッドかテンプレートメソッドかで持たせるのはむずかしい？

相談した結果、実装しない方向になりました。

2017-03-14 08:05 UTC, matsukawa1 commented on Sdx/Validation/Image/ValidatorSet.cs
> +}
相談の結果実装はしないことになりました。

2017-03-15 01:23 UTC, matsukawa1 commented on Sdx/Image.cs
> +      ICON = 128,
ここは、メイコーさんのコードをコピペしているので、念のため下記のメソッドの戻り値の値を全て確認する。

```
System.Drawing.Imaging.ImageCodecInfo.GetImageDecoders()
```

2017-03-15 01:27 UTC, matsukawa1 commented on Sdx/Image.cs
> +    public enum Format
Typeという名称にしていないのは、すでにTypeがプロパティで使用されているためです。

2017-03-15 06:53 UTC, matsukawa1 commented
## System.Drawing.Imaging.ImageCodecInfo.GetImageDecoders()の値を列挙する

```csharp
    foreach (System.Drawing.Imaging.ImageCodecInfo ici in System.Drawing.Imaging.ImageCodecInfo.GetImageDecoders())
    {
      Sdx.Context.Current.Debug.Log(ici.FormatDescription, "ici.FormatDescription");
    }
```
```
[0.00000000/1.41869282 sec] ici.FormatDescription c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\45d5cb9f\1024cae3\App_Web_m2lmmmyt.3.cs(23) - Page_Load
String(3) BMP


[0.00001956/1.41871238 sec] ici.FormatDescription c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\45d5cb9f\1024cae3\App_Web_m2lmmmyt.3.cs(23) - Page_Load
String(4) JPEG


[0.00000449/1.41871687 sec] ici.FormatDescription c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\45d5cb9f\1024cae3\App_Web_m2lmmmyt.3.cs(23) - Page_Load
String(3) GIF


[0.00000385/1.41872072 sec] ici.FormatDescription c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\45d5cb9f\1024cae3\App_Web_m2lmmmyt.3.cs(23) - Page_Load
String(3) EMF


[0.00000353/1.41872425 sec] ici.FormatDescription c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\45d5cb9f\1024cae3\App_Web_m2lmmmyt.3.cs(23) - Page_Load
String(3) WMF


[0.00000577/1.41873002 sec] ici.FormatDescription c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\45d5cb9f\1024cae3\App_Web_m2lmmmyt.3.cs(23) - Page_Load
String(4) TIFF


[0.00000353/1.41873355 sec] ici.FormatDescription c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\45d5cb9f\1024cae3\App_Web_m2lmmmyt.3.cs(23) - Page_Load
String(3) PNG


[0.00000321/1.41873676 sec] ici.FormatDescription c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\45d5cb9f\1024cae3\App_Web_m2lmmmyt.3.cs(23) - Page_Load
String(3) ICO
```

2017-03-16 10:02 UTC, gomo requested changes
enumとNULL許容型の件だけお願いします。

あと、テストがこけてるけど、確認しておいてください。
https://travis-ci.org/SunriseDigital/cs-sdx/builds/211259127

2017-03-16 10:02 UTC, gomo commented on Sdx/Image.cs
> +      ICON = 128,
口頭で相談したけんですけど、まあ、これは通常のenumでOKだね。

😇

2017-03-16 10:02 UTC, gomo commented on Sdx/Image.cs
> +    public Sdx.Image.Format? Type
ここはNULLが変えることはないと思うのでNull許容型じゃなくてOKだと思います。

```c#
return (Sdx.Image.Format)type;
```

😇

2017-03-16 10:02 UTC, gomo commented on Sdx/Validation/Image/Type.cs
> +    public Type(Sdx.Image.Format? jpeg = null, Sdx.Image.Format? png = null, Sdx.Image.Format? gif = null)
この辺もそうだね。基本的にNULL許容型はできるだけ外に公開しないほうがいい。

😇

2017-03-21 07:50 UTC, matsukawa1 commented on Sdx/Image.cs
> +    public Sdx.Image.Format? Type
修正完了

2017-03-21 07:50 UTC, matsukawa1 commented on Sdx/Validation/Image/Type.cs
> +    public Type(Sdx.Image.Format? jpeg = null, Sdx.Image.Format? png = null, Sdx.Image.Format? gif = null)
修正完了

2017-03-22 03:16 UTC, gomo approved these changes
いいと思います。テストがこけてるのは対応中ですよね？

2017-07-12 04:19 UTC, merged

2017-07-12 07:49 UTC, sunrise-matsumoto commented
# 本アップ完了しました