Bit型カラムを持つテーブルのORMクラス生成
SunriseDigital/cs-sdx pull request #118
Opened 2017-04-26 04:00 UTC by tkabeee

2017-05-08 08:55 UTC, gomo requested changes

2017-05-08 08:55 UTC, gomo commented on Sdx/Db/Adapter/SqlServer.cs
> +        {"bit", Table.ColumnType.Bit}
細かいですけど、Bitという単語からはデジタルデータの最小単位であるビットを思い浮かべちゃってBooleanという感じがしません。てか、SQLサーバーはどうしてそうしたんだ？という説もあるんですけど。BoolとかBooleanの方がしっくりくる感じがしました。

ネーミングの問題なので細かいですけど、SDXなので直してもらおうかな。お願いします。

SQLサーバーがBitなの気になってたんですよね。 先に言っておけばよかったですね。

😇

2017-05-08 10:14 UTC, tkabeee commented on Sdx/Db/Adapter/SqlServer.cs
> +        {"bit", Table.ColumnType.Bit}
> BoolとかBooleanの方がしっくりくる感じがしました。

SQLサーバーで Bit とされていたのでそのまま作業しておりましたが、こちらは私も同感です。
下記のコミットで修正対応いたしました。

https://github.com/SunriseDigital/cs-sdx/pull/118/commits/6be89eeb6a1dc913ea3d099193177ff685bd5b0a

2017-05-11 08:11 UTC, gomo approved these changes
👍 

まあ、bitは0|1しか値を取らないので、true/falseをbitとしたんでしょうけど・・・もしかしたら昔（アセンブラ？）は真偽値にbitを使うのが一般的だったけど、true/falseが何かの言語から導入されたとかですかね？

2017-07-04 07:47 UTC, merged