予約文字を含めたURLエンコード
SunriseDigital/cs-sdx pull request #121
Opened 2017-05-18 03:05 UTC by tkabeee

2017-05-25 03:18 UTC, tkabeee commented on Sdx/Util/String.cs
> +      str = HttpUtility.UrlEncode(str);
`%`もエンコード対象の為、先に実行するようにしました

2017-06-02 03:18 UTC, tkabeee commented on Sdx/Util/String.cs
> +        string reservedChars = "!*'();:@&=+$,/?#[]";
この reservedChars で指定している記号は 本来!()_-*. だけでいいんじゃないか（要チェック）

2017-06-02 03:20 UTC, gomo requested changes

2017-06-02 03:20 UTC, gomo commented on Sdx/Util/String.cs
> +        string reservedChars = "!*'();:@&=+$,/?#[]";
これは上のコメント`// !()_-*.以外の文字列がエンコードされます`と矛盾してるきがするので、おそらくどっちかが間違っていると思われます。確認お願います。

😇

2017-06-02 03:48 UTC, tkabeee commented on Sdx/Util/String.cs
> +        string reservedChars = "!*'();:@&=+$,/?#[]";
このコミットで修正対応しました
https://github.com/SunriseDigital/cs-sdx/pull/121/commits/1c9d4a5bc7eda2d1d1db564f5ac76686c087bfa0

やはり、`!()_-*.`以外の文字列がエンコードされるで間違いありませんでした

```csharp
//URLエンコードする文字列
string str = "!()_-*.aA0 ?#$%&|@\\/[]{}<>+=^~\"'`;:,あ";

//URLエンコードする
System.Web.HttpUtility.UrlEncode(str);

//結果
!()_-*.aA0+%3f%23%24%25%26%7c%40%5c%2f%5b%5d%7b%7d%3c%3e%2b%3d%5e%7e%22%27%60%3b%3a%2c%e3%81%82
```

2017-06-14 04:28 UTC, merged