Sdx.Data.Tree.Mapper
SunriseDigital/cs-sdx pull request #122
Opened 2017-05-22 08:01 UTC by katsuji-anzai

## 概要
・API等のレスポンスで利用しているSdx.Data.TreeJsonなどのTreeデータと、レコードセットを一つのクラスが持ち、使う為のクラスです。

2017-06-09 08:23 UTC, gomo requested changes

2017-06-09 08:23 UTC, gomo commented on Sdx/Data/TreeMapper/Record.cs
> +        public Record(Tree tree, Dictionary<string, Sdx.Db.RecordSet> recordSetList, Func<T, R, bool> condition)
３番目の引数がconditionというのが若干わかりづらい気がした。関数なのに名刺だし・・・

「レコードとツリーを結びつけるもの」って感じだと思うのでtreeRecordMatcherとかいいかも、あるいは単純にmatcherいいかな。

プロパティも含めてMatcherにしましょうか。他のところなら直すほどでもないけど、Sdxなので直しましょうか？

😇

2017-06-09 08:23 UTC, gomo commented on Sdx/Data/TreeMapper/Record.cs
> +        public Record(Tree tree, Dictionary<string, Sdx.Db.RecordSet> recordSetList, Func<T, R, bool> condition)
口頭で相談した件ですけど、こういうインターフェースははどうでしょうか？

```c#
var coupons = new Sdx.Data.TreeMapper.Record<Fzdb.Data.Tree.Coupon>(tree);
coupons.AddRecordSet<Fzdb.Orm.Main.Shop>(
  "shop"
  recordSet,
  (coupon, shop) => coupon.ShopId == shop.ShopId
)
```

あ、でもTypeオブジェクト使ってキャストがうまくできないかな・・・
やるなら下記のような感じになるんだけど、試してもらってもいいですか？

```c#
public void AddRecordSet<R>(string key, Sdx.Db.RecordSet recordSet, Func<T, R, bool> matcher) where R : Sdx.Db.Record
{
    recordSetDictionary[key] = new RecordSetData {
      RecordSet = recordSet,
      Matcher = matcher,
      Type = typeof(R)
    }
}
```

で、キャストはこんな感じ

```c#
private T CreateItem(Tree childTree)
{
    var treeItem = new T();
    treeItem.Tree = childTree;
    foreach(KeyValuePair<string, RecordSetData> pair in recordSetDictionary)
    {
      var data = pair.Value;
      treeItem.AddRecord(
        pair.Key,
        data.RecordSet
          .Select(rec => Convert.ChangeType(rec, data.Type))
          .FirstOrDefault(rec => data.Matcher(treeItem, rec))
      );
    }

    return treeItem;
}
```

Convert.ChangeTypeの返り値の型がobjectなのでだめかな〜だめなら下記も試してもらっていいですか？

```c#
     treeItem.AddRecord(
        pair.Key,
        data.RecordSet
          .Select(rec => (dynamic)Convert.ChangeType(rec, data.Type))
          .FirstOrDefault(rec => data.Matcher(treeItem, rec))
      );
```

ふむ・・・

ダメだったらMatcher内で毎回使うときにキャストして使うか・・・でもよく考えたら、Matcherの中の処理って、カラムを取得して見比べるだけなので、型がRecordでも問題ないかもしれないですね。

```c#
var coupons = new Sdx.Data.TreeMapper.Record<Fzdb.Data.Tree.Coupon>(tree);
coupons.AddRecordSet<Fzdb.Orm.Main.Shop>(
  "shop"
  recordSet,
  (coupon, shop) => coupon.ShopId == shop.GetInt32("shop_id")
)
```

一応上記のキャストを試してみてもらえますか？できても、できなくても、その時点で相談してください。



😇

2017-06-09 08:23 UTC, gomo commented on Sdx/Data/TreeMapper/Record.cs
> +        private Func<T, R, bool> Condition;
この辺の変数はすべて小文字始まりですね。プロパティじゃなくて、メンバー変数なので。

😇

2017-06-09 08:23 UTC, gomo commented on Sdx/Data/TreeMapper/Record.cs
> +        }
これはこっちのメソッドはいらないんじゃないでしょうか？コンストラクタに取り出したやつを渡せばいいだけですし。
そうなると、Treeがリストであることを前提にしたクラスになるので、コンストラクタでIsListみたいなので調べて例外にしちゃうのがいいと思います。

😇

2017-06-09 08:23 UTC, gomo commented on Sdx/Data/TreeMapper/Record/Item.cs
> +        public Tree Tree { get; set; }
このsetはアクセス修飾子をinternalにしたほうがいいですね。internalは同じアセンブリ無い、つまり、dllの中からのみアクセス可能なものです。結構使い所多いので覚えておいてください。

あるいはコンストラクタの引数にしてprivateにするか・・・そっちの方いいかな？

😇

2017-06-14 02:39 UTC, katsuji-anzai commented
@gomo 
前回レビュー時に出た、
* 変数名が大文字始まりにしてしまっていた件。
* ItemにセットするTree単体に該当するレコードを、レコードセットから取得する為の条件が1つしか渡していなかった件。
* GetItemsの引数無し・引数ありを用意したが、コンストラクタで目的のTree階層を渡しておけば、引数ありは必要ない。という改修の件。

こちらの修正をしました。
再レビューお願いします。

2017-06-14 07:56 UTC, gomo requested changes

2017-06-14 07:56 UTC, gomo commented on Sdx/Data/TreeMapper/Record.cs
>              }
すごい細かいですけど、このrecordSetDictionaryは遅延初期化する必要はないですね。なぜなら、このクラスを使うときにこのディクショナリを使わないことがありえないので。どちらかというと、このメソッドを複数回読んだときIF文の処理分計算量が無駄になるので、遅延初期化しないほうがいいということになります。

まあ、細かいですけどSDXなんで直してもらおうかな。細かいけど、考え方として結構大事なんですよね。「全てに理由がある」という考え方。まあ、もちろん理由のないどっちでもいいことってありますけど、それを考えてみるというのは設計の基本です。

😇

2017-06-14 07:56 UTC, gomo commented on Sdx/Data/TreeMapper/Record.cs
> +        public class RecordSetData
このクラスは公開する必要はなさそう。後悔しないように直して起きましょうか・・・ 🤓 

```c#
private class RecordSetData
```

privateでいけるかな？だめだったらinternalで。

😇

2017-06-14 07:56 UTC, gomo commented on Sdx/Data/TreeMapper/Record.cs
> +        public void AddRecordSet(string key, Sdx.Db.RecordSet recordSet, Func<T, Sdx.Db.Record, bool> matcher)
口頭で話した件です。例えば、Item.CouponにShopプロパティを作るとすると

```c#
public Orm.Main.Shop Shop
{
  get
  {
    return (Orm.Main.Shop)GetRecord("shop")
  }
}
```
みたいなメソッドになると思いますが、AddRecordSetするのはクライアントコード書く人で、その人が`shop`以外の名前でAddしてしまうというか、いちいち、名前なんだっけ？って見に行かないとAddできないのが気持ち悪いですね。

プロパティ生やすのやめちゃえば、なんとなく筋が通りますが、ORMのレコードは具象クラスで扱うのが基本なのでできればプロパティ生やしたいですね。取得時にキャストするのも手だとは思いますけど・・・

まず、キーを表現するクラスを作ります。これはアイテムのインナークラスでいいかな。

```c#
public class RecordKey
{
  public string Code{get; private set;}
  public RecordKey(string code)
  {
    Code = code;
  }

  public override int GetHashCode()
  {
    return Code.GetHashCode();
  }
  
  public override bool Equals(object obj)
  {
    return Equals(obj as RecordKey)
  }

  public bool Equals(RecordKey recordKey)
  {
    return recordKey != null && recordKey.Code == this.Code;
  }
}
```
overrideされてるメソッドはDictiornaryのキーにするために必要です。で、Tree.Couponに

```c#
public class Coupon : Sdx.Data.TreeMapper.Record.Item
{
  public static readonly RecordKey ShopKey = new RecordKey("shop")
```

で使うときはこんな感じ

```c#
treeMapper.AddRecordSetData(Coupon.ShopKey, recordSet, (coupon, shop) => coupon.ShopId == shop.GetInt32("shop_id"))
```

別のItemにまたShopがあったときこのキーはEqualを返しちゃうのが気持ち悪いけど、とりあえず、一つのTreeMapperに複数のItemが関連づくことはないので、Coupon内でRecordKey.Codeが重複しなければOKですね。

これを厳密にするなら、RecordKeyを抽象クラスにして、Coupon内に継承たRecordKeyCounpon的なものを作って、GetHashCodeとEqualsでクラスも考慮すれば同じクラス内でしか一致しないことになる・・・（一旦考えます）

Sdx.Data.TreeMapper.Record.Itemにはチェック用のメソッドを用意する

```c#
  public bool HasRecordKey(RecordKey recordKey)
  {
    return this.GetType().GetProperties()
      .Where(prop => prop.IsStatic)
      .Where(prop => prop.PropertyType == typeof(RecordKey))
      .Any(prop => {
        var val = prop.GetValue(null, null) as RecordKey
        return val != null && val.Equals(recordKey)
      })
  }
```

このメソッドは多分動くという次元w自信ないのでここを先に試してください。これができないと独自クラスを作る意味がないので。

Stringを使わずわざわざキー用のクラスを作るのは下記の理由です。

* AddRecordSetDataで型チェックが可能
* Itemにチェック用メソッドを作るのに、プロパティとは持っているRecordKeyとは別に配列を宣言しなくて済む。

2017-06-14 09:13 UTC, katsuji-anzai commented on Sdx/Data/TreeMapper/Record.cs
>              }
なるほど・・・確かに、宣言する時に作ってしまえばOKですね。
> このメソッドを複数回読んだときIF文の処理分計算量が無駄になる
この考え方も、勉強になります。
今後も、なるべく気をつけて考えるようにします。

2017-06-16 06:19 UTC, katsuji-anzai commented
@gomo 

再レビューで出た下記部分修正しましたので、確認お願いします。
* レコードセットと対になるキー指定をする際、内部クラスRecordKeyを引き回す仕様に変更
* Item.Couponの名前空間が微妙だったので、Fzdb.Data.TreeMapper.Record.Item.Couponに修正。

以上です。
よろしくお願いします。

2017-06-19 05:09 UTC, gomo requested changes

2017-06-19 05:09 UTC, gomo commented on Sdx/Data/TreeMapper/Record/Item.cs
> +            throw new ArgumentException("Argument 'key' is invalid. It must be of type 'RecordKey'.");
ちょっと前のミーティングで共有したけど、これはエラーメッセージが不親切というか不正確ですね。

まず、ここに来てるのに、typeがRecordKeyじゃないことはないので`It must be of type 'RecordKey'.`というのは？？となります。あと話がそれるけど英文的に変かな？（私もあまり得意じゃないので言うのもなんですが）

`It must be RecordKey type.`

の方がしっくりくるかも。Google翻訳を活用すると作文の練習になるので活用してください。最近コツがわかって来たのですが、主語や目的語を省略しないでしっかり日本語を入力すると割と正確な英語が出ると思います。あと、自分の知らない単語は極力知ってる簡単な単語に置き換えるといいです。

あと、これは「引数に指定したRecordKeyがこのアイテムのプロパティに設定してないですよ〜」というエラーなので、

```c#
throw new ArgumentException("Missing `" + key.Code + "` RecordKey property in this item.");
```

とか、意味をそんな感じにするのと、何よりも何が与えられてるのか`key.Code`で出してあげた方がいいですね。一番大事なのはエラーメッセージに`key.Code`を含んであげることです。

😇

2017-06-19 05:09 UTC, gomo commented on Sdx/Data/TreeMapper/Record/Item.cs
> +              return val != null && val.Equals(recordKey);
Equalsの実装を見ると

```c#
.Any(prop => recordKey. Equals(prop.GetValue(null)))
```
で問題なさそうだね。ただ、recordKeyがNULLがくるとこけるので、防御してやる必要があるけど・・・

```c#
public bool HasRecordKey(RecordKey recordKey)
{
    if(recordKey == null)
    {
      throw new ....
    }
```

としてやるのがいいかな。return falseどどっちがいいかな・・・基本的にNULLは想定してないと思うので例外がいいかな。

😇

2017-06-19 05:31 UTC, katsuji-anzai commented on Sdx/Data/TreeMapper/Record/Item.cs
> +            throw new ArgumentException("Argument 'key' is invalid. It must be of type 'RecordKey'.");
書いていて、このエラー文、微妙・・・と思ったのですが。
なんていう説明をするのが良いのかが、どうしても思いつかなくて、
そもそも、ここで返すエラーは、
「RecordKeyとして認められているものを渡してないですよ」
ではなく、
「RecordKeyの"key.Code"の指定が間違っていますよ」
なんですね。

言われてみると分かるんですが・・・。

ここでエラーを返す意図を、はっきり把握してない状態だったから、うまいエラーメッセージが導き出せなかったのかなぁ・・・って思います。

2017-06-19 06:13 UTC, katsuji-anzai commented
下記修正しました。
・例外の文章を、明確に。
・HasRecordKey内で、recordKeyがnullの時は例外を返すように。

再レビューお願いします。

2017-06-19 07:41 UTC, gomo approved these changes
👍

2017-07-12 04:20 UTC, merged

2017-07-12 07:49 UTC, sunrise-matsumoto commented
# 本アップ完了しました