Scaffold に Save 後に動作するフックを追加する
SunriseDigital/cs-sdx pull request #127
Opened 2017-06-27 01:33 UTC by tomita-ychr

## 概要
保存後に特定の動作させたい状況ができたため、フックを追加して対応します。

2017-06-28 01:07 UTC, tomita-ychr commented
```C#
AddPostUpdateHook(params UpdateTypes[] types, Action<??> callback)
```
この案は types が最後の引数でないと使えなかった。
https://msdn.microsoft.com/ja-jp/library/aa645761(v=vs.71).aspx

なので別の方法を考える。

2017-06-28 04:23 UTC, tomita-ychr commented
@gomo 
こんなかんじで進めてみようかと考えていますがいかがでしょうか？
お手すきの際にご確認ください。

## 予定
### Update 種別
Update 種別指定用のEnumを作っておきます。
名前はEditTypesでもいいかもしれません。
```C#
public enum UpdateTypes
{
  Insert,
  Update,
  Delete
}
```

### 追加メソッド
可変長引数を使うのは諦めて、配列で渡す方向にします。
Action の引数は使いそうなものを仮で書いてます。
```C#
AddPostUpdateHook(IEnumurable<UpdateTypes> types, Action<Sdx.Db.Sql.Select, Sdx.Db.Connection> callback)
```

### フックを仕込む場所
Insert, Update のフックはSaveメソッドの最下部あたりに。
https://github.com/SunriseDigital/cs-sdx/blob/fa002dfc05ba2fc0301d8df025ad985818eef33b/Sdx/Scaffold/Manager.cs#L343-L383

Delete はDeleteRecordメソッドの最下部あたりに。
https://github.com/SunriseDigital/cs-sdx/blob/fa002dfc05ba2fc0301d8df025ad985818eef33b/Sdx/Scaffold/Manager.cs#L448-L460

2017-06-28 05:42 UTC, tomita-ychr commented
## メモ
https://github.com/SunriseDigital/cs-sdx/pull/127#issuecomment-311552874
上記について gomo さんとも相談して決まった方針をメモします。

- UpdateTypes を渡すのはやめて、フックは別々にする。
- 今回は Save (新規、更新時に呼ばれる)用のフックだけを追加する。

インターフェースは以下のようなかんじで。
```C#
AddPostSaveHook(Action<Sdx.Db.Record record, NameValueCollection values, Sdx.Db.Connection conn, bool newOnly> callback)
```

2017-07-05 01:55 UTC, tomita-ychr commented
## Travis だけで出るエラー
以下の2つのテストがコケる。ローカルでは問題なく通る。Why？
```
UnitTest.Scaffold_Manager.TestGroupingStaticClass [FAIL]
   System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection.
   Parameter name: index
   Stack Trace:
     at System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) [0x00029] in <a07d6bf484a54da2861691df910339b1>:0 
     at System.ThrowHelper.ThrowArgumentOutOfRangeException () [0x00000] in <a07d6bf484a54da2861691df910339b1>:0 
     at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x00009] in <a07d6bf484a54da2861691df910339b1>:0 
     at UnitTest.Scaffold_Manager+<>c__DisplayClass9_1.<RunGroupingStaticClass>b__6 (Sdx.Db.Record rec) [0x0000b] in <d732c0883ff8447a91963c4f46814832>:0 
     at Sdx.Db.RecordSet+<>c__DisplayClass16_0.<ForEach>b__0 (System.String key, Sdx.Db.Record rec) [0x00000] in <49d40d1b862d4cc68c460ec4dcd37d10>:0 
     at Sdx.Collection.OrderedDictionary`2+<>c__DisplayClass23_0[TKey,TValue].<ForEach>b__0 (TKey key) [0x00019] in <49d40d1b862d4cc68c460ec4dcd37d10>:0 
     at System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) [0x00024] in <a07d6bf484a54da2861691df910339b1>:0 
     at Sdx.Collection.OrderedDictionary`2[TKey,TValue].ForEach (System.Action`2[T1,T2] action) [0x00027] in <49d40d1b862d4cc68c460ec4dcd37d10>:0 
     at Sdx.Db.RecordSet.ForEach (System.Action`1[T] action) [0x0000e] in <49d40d1b862d4cc68c460ec4dcd37d10>:0 
     at UnitTest.Scaffold_Manager+<>c__DisplayClass9_0.<RunGroupingStaticClass>b__4 () [0x00126] in <d732c0883ff8447a91963c4f46814832>:0 
     at UnitTest.Scaffold_Manager.RunGroupingStaticClass (UnitTest.BaseDbTest+TestDb db) [0x000a6] in <d732c0883ff8447a91963c4f46814832>:0 
     at UnitTest.Scaffold_Manager.TestGroupingStaticClass () [0x00016] in <d732c0883ff8447a91963c4f46814832>:0 
     at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
     at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <a07d6bf484a54da2861691df910339b1>:0
```
```
UnitTest.Scaffold_Manager.TestGroupingTableMeta [FAIL]
   Assert.Equal() Failure
   Position: First difference is at position 127
   Expected: <select name="large_area_id"><option value="">絞り込む</option><option value="1" selected>東京</option><option value="2">愛知</option></select>
   Actual:   <select name="large_area_id"><option value="">絞り込む</option><option value="1" selected>東京</option><option value="2">愛知</option><option value="3">test_large_area__update</option></select>
   Stack Trace:
     at UnitTest.Scaffold_Manager+<>c__DisplayClass7_0.<RunGroupingTableMeta>b__4 () [0x000bc] in <d732c0883ff8447a91963c4f46814832>:0 
     at UnitTest.Scaffold_Manager.RunGroupingTableMeta (UnitTest.BaseDbTest+TestDb db) [0x000a6] in <d732c0883ff8447a91963c4f46814832>:0 
     at UnitTest.Scaffold_Manager.TestGroupingTableMeta () [0x00016] in <d732c0883ff8447a91963c4f46814832>:0 
     at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
     at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <a07d6bf484a54da2861691df910339b1>:0
Tests complete: 191 of 220FixtureTearDown
220 total, 2 failed, 0 skipped, took 4.254 seconds
```

2017-07-05 02:33 UTC, tomita-ychr commented
> Travis だけで出るエラー

テスト中に Insert したレコードを、テスト終了時に掃除するようにしたら想定どおりエラーが改善した。2つ出ていたエラーはどちらも同じ原因だった。

2017-07-06 02:07 UTC, gomo requested changes

2017-07-06 02:07 UTC, gomo commented on Sdx/Scaffold/Manager.cs
> +      }
遅延初期化すると、AddでもSaveでもあるかどうかチェックしないといけないので無駄なIF文が増えて読みづらくなるし、呼ばれるたびに毎回IF文が評価されるので計算量も増えます。例えばDBの接続とか、ファイルのロックとか、外部へのHTTP問い合わせなど、コストの高い時以外しない方だいいです。あるいはNULLか空のLISTか、によって挙動を変えたい時ですね。

細かいけど、これは直してもらおうかな。

あとついでと言ってはなんですけど、PostSaveHookListはメンバー変数なので小文字始まりにすべきですね。これもついでにお願いします。

😇

2017-07-06 02:07 UTC, gomo commented on UnitTest/Sdx/Scaffold/Manager.cs
> +          }
例外を捕まえて投げるだけならこのtry文はいらないですね。まあ、でもいいか。このままで。これ、誰か他の人のレビューでも書いた記憶があるな（とかいって富田くんだったりしてw）。なんとなくtry文で囲ってないと安心感が出ないんですかね？あるいは、最初ロールバックしていて、やめてtryだけ残ったとかかな？

2017-07-06 02:07 UTC, gomo commented on UnitTest/Sdx/Scaffold/Manager.cs
> +          }
非常に真面目なテストいいと思います。DBに保存してみた方がいいですもんね 👍

2017-07-06 02:21 UTC, tomita-ychr commented on UnitTest/Sdx/Scaffold/Manager.cs
> +          }
> あるいは、最初ロールバックしていて、やめてtryだけ残ったとかかな？

あ、完全にそれです。。。
Save 内の例外は↓で捕まえているので要らなそうですね。他の修正があるのでその際に直しますー
https://github.com/SunriseDigital/sdxweb/blob/master/cs/scaffold/edit.ascx.cs#L50

2017-07-06 02:28 UTC, tomita-ychr commented on Sdx/Scaffold/Manager.cs
> +      }
List の生成コストをケチった結果、IF文の評価コストが増えて本末転倒なかんじですね。仰るとおりなので修正しますー

> PostSaveHookListはメンバー変数なので小文字始まりにすべきですね。

間違えてました。こちらもあわせて修正します。

2017-07-06 04:55 UTC, gomo approved these changes

2017-08-24 07:15 UTC, merged