ポイントボーナスキャンペーンの条件変更
SunriseDigital/cs-sdx pull request #143
Opened 2017-11-06 04:11 UTC by naveqo

## Pivotal
https://www.pivotaltracker.com/story/show/151940683

## 関連するPR/Issue

### 親PR
https://github.com/SunriseDigital/nukinavi_unified/pull/629

## Page
https://shutoken.nukinavi.com/admin/master/point_campaign/

## チェック
- [ ] 作業可所に関して、本アップ前・本アップ後の画面ショットをPRに付ける

## TODO

### 一般
- [ ] ページ表示速度は遅くないか？
- [ ] イベントトラッキングは必要か？
- [ ] 更新チームへの周知が必要か？
- [ ] クライアント・営業周知は必要か？
- [ ] サイトナビ・お店管理画面とヌキなびのインフォは必要か？
- [ ] 管理画面を止める必要はあるか？

### SEO
- [ ] [ページのタイトル・h1・デスクリプションは適切か？](https://github.com/SunriseDigital/sunrise/wiki/SEOを意識したページ作り#ページのタイトルh1デスクリプション)
- [ ] [対象ページへのリンクは適切か？](https://github.com/SunriseDigital/sunrise/wiki/SEOを意識したページ作り#対象ページへのリンク)
- [ ] [ソフト404になるページはないか？](https://github.com/SunriseDigital/sunrise/wiki/SEOを意識したページ作り#ソフト404)
- [ ] [URLの正規化はされているか？](https://github.com/SunriseDigital/sunrise/wiki/SEOを意識したページ作り#urlの正規化について)
- [ ] [外部リンクにnofollowを設置しているか？](https://github.com/SunriseDigital/sunrise/wiki/SEOを意識したページ作り#nofollowの設置について)
- [ ] [隠しテキストになっていないか？](https://github.com/SunriseDigital/sunrise/wiki/SEOを意識したページ作り#隠しテキストを使用しない)
- [ ] [ファイル容量は大きすぎないか？](https://github.com/SunriseDigital/sunrise/wiki/SEOを意識したページ作り#ファイル容量は極力軽くするラフデザイン)
- [ ] [テキスト量は十分か？](https://github.com/SunriseDigital/sunrise/wiki/SEOを意識したページ作り#テキスト量は十分かラフデザイン)
- [ ] [サイトマップの変更は必要か？](https://github.com/SunriseDigital/sunrise/wiki/SEOを意識したページ作り#サイトマップの変更について)
- [ ] [エンコードされたURLのリンク設置方法は適切か？](https://github.com/SunriseDigital/sunrise/wiki/SEOを意識したページ作り#エンコードされたurlのリンクを設置する際の注意点)

2017-11-08 04:08 UTC, gomo requested changes

2017-11-08 04:08 UTC, gomo commented on Sdx/Scaffold/Config/Value.cs
> +        return method;
ここは一度変数に入れる必要はなさそうですね。
代入にも計算量が1かかるので必要なのであればしない方がいいです。まあ、微々たるもんなんですけど。

まあ直すほどでもないけどついでがあったら直してもらおうかな。

```rb
return type.GetMethod(value.ToString());
```

🐒

2017-11-08 04:08 UTC, gomo commented on Sdx/Scaffold/Config/Value.cs
> +        return property;
こちらもですね。まあ、上のコード使いまわしたからだけど。ただ、こういうことに神経を研ぎ澄ませとくのはいいことです。

2017-11-08 04:08 UTC, gomo commented on Sdx/Scaffold/Manager.cs
> +                args.Add(values);
`args.Add(values)`は必要なさそうですね。

上のメソッドでこれが必要な理由は、サブミットされた他の値をつかって何かをしたい時のためにメソッドに２つの引数を宣言して扱える様になってるからですね。

```cs
.Set("setter", new Sdx.Scaffold.Config.Value("FooBar"))
...
namespace Test.Orm
{
  public class Area : Sdx.Db.Record
  {
    public void FooBar(string value, NameValueCollection values)
    {
       //こういう風に宣言しておくと、全てのサブミットされた値が取れるんです。
    }
```

プロパティは値の代入しかないので
```cs
propertyInfo.SetValue(record, args[0]);
```

だけすればOKです。

😇

2017-11-08 04:08 UTC, gomo commented on UnitTest/Sdx/Scaffold/Manager.cs
> +      string savedId;
この宣言は必要ないですね。C#の変数はブロック変数なのでusingの中で使うなら必要ないです。

下記の場合は必要です。

```cs

      string savedId;
      using (var conn = scaffold.Db.CreateConnection())
      {
        ...
        savedId = record.GetString("id");
      }

      var savedRecord = (new Test.Orm.Table.Area()).FetchRecordByPkey(conn, savedId);
      Assert.Equal("new", savedRecord.GetString("name"));
      Assert.Equal("test", savedRecord.GetString("code"));
```

コピー元もこうなってるので、コピー元もおそらくどっかのテストをコピーしたのでそうなってるんでしょうw
まあ、ついでがあったら直しておいてください。

知識としては知っておいてください。

ちなみに、変数のスコープは言語によって微妙に違うので気をつけてくださいね。C#は、という話です。PHPやJSなど型にゆるい言語はifとかforなどのブロックの中で宣言した変数が外で使えちゃったりします。関数ブロックはつかません。そういう言語はC#のブロックスコープと対比して関数スコープと言ったりします。

🐒

2017-11-08 04:08 UTC, gomo commented on UnitTest/Sdx/Scaffold/Manager.cs
> +      post.Set("type", "new");
とりあえず、ここまでできたので、ここを配列に変更してみてください。

```cs
post.Add("type", "foo")
post.Add("type", "bar")
post.Add("type", "baz")
```

でアサート（保存後の結果）は

```
Assert.Equal("new", savedRecord.GetString("foo_bar_baz"));
```
となる様にテストを変更してみてください。

😇

2017-11-08 04:22 UTC, naveqo commented on Sdx/Scaffold/Config/Value.cs
> +        return method;
確かに必要ないですね。。詰めが甘かったです。。。
修正承知しました。

2017-11-08 05:03 UTC, naveqo commented on Sdx/Scaffold/Manager.cs
> +                args.Add(values);
> 上のメソッドでこれが必要な理由は、サブミットされた他の値をつかって何かをしたい時のためにメソッドに２つの引数を宣言して扱える様になってるからですね。

何故`Count() == 2`なんだろう？って思ってました。
`methodInfo.GetParameters()`をダンプして謎が解けました。

> //こういう風に宣言しておくと、全てのサブミットされた値が取れるんです。

これが微妙に理解出来てないので後で聞きに行きます！！

2017-11-08 07:11 UTC, naveqo commented on UnitTest/Sdx/Scaffold/Manager.cs
> +      string savedId;
`savedId`変数を使わない形で修正しました。

2017-11-09 03:06 UTC, gomo requested changes

2017-11-09 03:06 UTC, gomo commented on Sdx/Scaffold/Manager.cs
> +                propertyInfo.SetValue(record, values.GetValues(columnName));
おしいなあw

これをしちゃうと、前の文字列が動かなくなっちゃうんですよね。そういう意味ではテストをもう一個追加するとよかったですね。そうすれば動かなくなったことに気づいたので。

ヒントはここです。
https://github.com/SunriseDigital/cs-sdx/blob/65ebcea36887df5da70e4936c3ae1e7406194444/Sdx/Scaffold/Manager.cs#L361-L368

配列用と文字列用両方テストしましょうか？前のテストもまるっとコピーして持って来て、ヒントを参考にテストが両方通る様にしてください。

https://github.com/SunriseDigital/cs-sdx/blob/e83f2a678d3c2f911f628b477609abf9ab6f0db2/UnitTest/Sdx/Scaffold/Manager.cs#L1496-L1552

😇

2017-11-09 06:27 UTC, naveqo commented on Sdx/Scaffold/Manager.cs
> +                propertyInfo.SetValue(record, values.GetValues(columnName));
ああ。。なるほど。
承知しました。

2017-11-10 01:29 UTC, gomo requested changes

2017-11-10 01:29 UTC, gomo commented on Sdx/Scaffold/Manager.cs
> +                if (propertyInfo.PropertyType.Name.Contains("[]"))
ああ、なるほど。こういう判断方法もないことはないけど・・・

ヒントで送ったコードを見て見てください。

https://github.com/SunriseDigital/cs-sdx/blob/dcf3b976b4f98ccdc9069723e1e690b712bc9b58/Sdx/Scaffold/Manager.cs#L361-L368

関数の時と判断基準が変わってしまうとややこしくないですか？関数の時も同じ様に変更するならなくはないですけど、わざわざ仕様を変更する積極的な理由がないですね。既存のコードにも影響するし。

あと、この送ったヒントは「関数の時は」というIF文に入ってないですよね。つまり、プロパティの時も使えるということです。で、その判断基準はどうなってるかというと、設定項目の中に`multiple`という値が`true`である場合は強制的に配列でセットするようになっています。スカッフォールドの使用時に明示的に指定するような仕様になっているということです。

プロパティの時も同じ方法が使えます。

```c#
      scaffold.FormList
        .Add(Sdx.Scaffold.Config.Item.Create()
          .Set("label", new Sdx.Scaffold.Config.Value("タイプ"))
          .Set("name", new Sdx.Scaffold.Config.Value("type"))
          .Set("multiple", new Sdx.Scaffold.Config.Value(true))
          .Set("setter", new Sdx.Scaffold.Config.Value("Types"))
        )
```

😇

2017-11-10 06:58 UTC, naveqo commented on Sdx/Scaffold/Manager.cs
> +                if (propertyInfo.PropertyType.Name.Contains("[]"))
まったくもって勘違いしておりました。。
承知しました！元に戻します！！

2017-11-10 09:53 UTC, gomo approved these changes
👍

2017-11-15 05:55 UTC, gomo requested changes

2017-11-15 05:55 UTC, gomo commented on Sdx/Scaffold/Manager.cs
> +              if (args != null) {
こちらも同じくいらないさそう。


```c#
              var propertyInfo = config["setter"].ToPropertyInfo(record.GetType());
              propertyInfo.SetValue(record, args[0]);
```



あと細かいですけどc#のIFはこんな感じで書くことになってます。言語によって推奨の書き方が違って、今のところ一応合わせてるので気をつけてください。まあ、これだけだったら修正しろとは言いませんけど。ついでに直してもらおうかな。

```c#
if (args != nulll)
{

}
```

😇

2017-11-15 05:55 UTC, gomo commented on Sdx/Scaffold/Manager.cs
> +              if (args != null)
このIF文は必ずTRUEになりますね。
https://github.com/SunriseDigital/cs-sdx/blob/f6cb333afb5a10c49d186181a4cd0e50dffc418e/Sdx/Scaffold/Manager.cs#L356
ここで初期化してるので。

たぶん
```c#
if (args[0] != null) { 

```
と勘違いかな？
でも、そもそもこのIF文はいらないんじゃないでしょうか？

```c#
            if (config["setter"].ToMethodInfo(record.GetType()) != null)
            {
              var methodInfo = config["setter"].ToMethodInfo(record.GetType());
             
              if (methodInfo.GetParameters().Count() == 2)
              {
                args.Add(values);
              }

              methodInfo.Invoke(record, args.ToArray());
            }
```

どうでしょう？


😇

2017-11-15 05:55 UTC, gomo commented on Sdx/Scaffold/Manager.cs
> +            if (values[columnName] != null) {
このIF文もいらないんじゃないかな？
これがNULLになるということは、checkbox/radio/selectタグの時だけで、それが空の時はカラムをNULLにしちゃって良さそうですし・・・

カラムがNOT NULLで、空の時に空文字や0に更新したいシチュエーションがないとも限らないけど、そういうのはカラムの設定値から取って自動で調整するのがいいのかな。それがベストですね。

コメント書いておいてください。

```c#
// チェックボックスなどで`values[columnName]`がNULLの時、カラムをNULLに更新しようとします。
// TODO テーブルからカラムの設定を取り出してヌルを許容していない場合、型に応じて0か空文字などを入れる必要があります。
record.SetValue(columnName, values[columnName]);
```

😇

2017-11-16 04:54 UTC, naveqo commented on Sdx/Scaffold/Manager.cs
> +              if (args != null)
> このIF文は必ずTRUEになりますね。

確認したところ必ずNULLになりました。
確認不足でした、すみません。。

2017-11-16 04:55 UTC, naveqo commented on Sdx/Scaffold/Manager.cs
> +              if (args != null) {
> あと細かいですけどc#のIFはこんな感じで書くことになってます。言語によって推奨の書き方が違って、今のところ一応合わせてるので気をつけてください。まあ、これだけだったら修正しろとは言いませんけど。ついでに直してもらおうかな。

承知しました。
以後気をつけて書くようにします！

2017-11-16 04:55 UTC, naveqo commented on Sdx/Scaffold/Manager.cs
> +            if (values[columnName] != null) {
承知しました。

2017-11-20 08:03 UTC, gomo approved these changes
👍

2017-11-28 01:58 UTC, merged