GroupByがある場合のOrderの除外方法
SunriseDigital/cs-sdx pull request #88
Opened 2016-11-15 04:31 UTC by tkabeee

## 概要

- GroupByに無いカラムでも、カラムリストに設定されていればOrderから取り除かないようにします

2016-11-15 06:01 UTC, tkabeee commented
## 変更が必要になった事例について

日記アクセスランキングでは、集計関数でアクセスカウントを集計したカラムを降順ソートしてランキングとしています

問題となるのは、selectをビルドした際に以下の行でOrderListからソートオーダーが除外されてしまう点です
https://github.com/SunriseDigital/cs-sdx/blob/master/Sdx/Db/Sql/Select.cs#L379-L386

```csharp
//Group Byに無いカラムは自動的にOrderから取り除かれます。
//SELECT句はからは取り除きません。DBベンダーによっては取得できますし、意味がないわけではないので。
if (groups.Count > 0)
{
  orders = orders
    .Where(orderCol => groups.Any(groupCol => orderCol.SameAs(groupCol)))
    .ToList<Column>();
}
```
- グループ化されているカラムは除外されないようになっています
- 集計カウントカラムをグループ化してしまうとランキング内に女の子が重複してしまいます
- グループ化されているカラムではなく、カラムリストに存在するカラムを比較対象とすれば、取り除く目的は保持したまま問題を解決できるのではと思います

## 日記アクセスランキングのコード

### 集計カウント用カラムを追加
https://github.com/SunriseDigital/cs-fuzoku/blob/proj/fzdbRankingFixSum/Fzdb/Ranking/Base.cs#L203-L204

```csharp
select.AddColumn(Sdx.Db.Sql.Expr.Wrap("SUM(" + AliasNameForAccessRankingCount + ".cnt)"), "sum_count");
```

### 集計用グループ化
https://github.com/SunriseDigital/cs-fuzoku/blob/proj/fzdbRankingFixSum/Fzdb/Ranking/Base.cs#L217
https://github.com/SunriseDigital/cs-fuzoku/blob/proj/fzdbRankingFixSum/Fzdb/Ranking/Base.cs#L221

```csharp
cRankingCount.AddGroup("type");
```

```csharp
cFrom.Table.OwnMeta.Columns.ForEach(col => cFrom.AddGroup(col.Name));
```

### カウント集計結果で降順ソート
https://github.com/SunriseDigital/cs-fuzoku/blob/proj/fzdbRankingFixSum/Fzdb/Ranking/Base.cs#L264-L265

```csharp
select.AddOrder("sum_count", Sdx.Db.Sql.Order.DESC);
```

2016-11-16 02:37 UTC, gomo requested changes

2016-11-16 02:37 UTC, gomo commented on Sdx/Db/Sql/Select.cs
> +          .Where(orderCol => columns.Any(col => orderCol.SameAs(col)))
```c#
      //Group Byに無いカラムは自動的にOrderから取り除かれます。
      //SELECT句はからは取り除きません。DBベンダーによっては取得できますし、意味がないわけではないので。
      if (groups.Count > 0)
      {
        var allowList = columns.Union(groups);
        orders = orders
          .Where(orderCol => allowList.Any(col => orderCol.SameAs(col)))
          .ToList<Column>();
      }
```

にしないとだめじゃなかろか？Group句にいれたカラムをSELECT句に入れてない可能性があるので。

2016-11-16 07:01 UTC, tkabeee commented on Sdx/Db/Sql/Select.cs
> +          .Where(orderCol => columns.Any(col => orderCol.SameAs(col)))
@gomo 

> Group句にいれたカラムをSELECT句に入れてない可能性がある

おっしゃる通りです。 必ずしもSELECT句にグループ化されたカラムが指定されているとは限りませんでした。

```csharp
var allowList = columns.Union(groups);
```

このUnionメソッドで columns と groups の和集合を生成できるのですね。勉強になります。
こちらのコードで対応いたします。

2016-11-17 03:01 UTC, gomo commented on Sdx/Db/Sql/Select.cs
> +          .Where(orderCol => columns.Any(col => orderCol.SameAs(col)))
C#でWEB開発はイマイチな感じがしてるんだけど、C#自体は良くできた言語ですよね。LINQ大好き。すごい便利。PHPにも似たの作ろうかな。てか、すでにあるかもね。似た感じのライブラリ。

2016-11-17 03:06 UTC, gomo commented on Sdx/Db/Sql/Select.cs
> +          .Where(orderCol => columns.Any(col => orderCol.SameAs(col)))
http://qiita.com/rana_kualu/items/2022739d8559272640bc
やっぱりあった。

2016-11-17 03:07 UTC, gomo approved these changes

2016-11-17 03:09 UTC, gomo commented
[![LGTM](https://lgtm.in/p/a7nqaQMzn)](https://lgtm.in/i/a7nqaQMzn)

2016-11-17 06:16 UTC, merged