Sdx.Web.DeviceTableの実装
SunriseDigital/cs-sdx pull request #90
Opened 2016-11-18 10:02 UTC by shimizu-k-digi

設定ファイルを読み込んでURLが一致してるか見る

2016-11-29 02:31 UTC, shimizu-k-digi commented
### あと抜けてる実装と修正必要ありそうな箇所メモ
・query_matchがなかったらそもそもqueryを見に行かなくてよい
・query_matchがあったらqueryを見に行くがkeyを置き換える必要があるかないかを見る

2016-12-01 02:05 UTC, gomo commented
そんなにがっちりじゃなくていいので簡単なドキュメントお願いします。

ここに目次追加
https://github.com/SunriseDigital/cs-sdx/tree/master/Sdx/Web

DeviceTable.mdにドキュメント書いてください。

参考
https://github.com/SunriseDigital/cs-sdx/blob/master/Sdx/Db/Sql/Select.md

「概要」に何をするものなのか。使い方に、使い方。今回はコードだけでなくyamlのフォーマットも乗せるといいと思います。

2016-12-05 07:02 UTC, gomo requested changes

2016-12-05 07:02 UTC, gomo commented on Sdx/Web/DeviceTable.md
> +URLがyaml形式の対応表に存在するかチェックをし、存在した場合各デバイスに対応したURLを取得できます。
> デバイス毎にURLが違う場合に、その対応表を管理します。

とかなんとかあったほうがいいかも。

> デバイス毎にURLが違う場合にその対応表を管理します。URLがyaml形式の対応表に存在するかチェックをし、存在した場合各デバイスに対応したURLを取得できます。

😇

2016-12-05 07:02 UTC, gomo commented on Sdx/Web/DeviceRedirectHttpModule.cs
> +        if (Regex.IsMatch(userAgent, smartPhoneUa))
ここは頻繁に実行されるのでコンパイル済みの正規表現にしたほうがいいと思います。
😇

2016-12-05 07:02 UTC, gomo commented on Sdx/Web/DeviceTable.cs
> +      Regex regex = new Regex(@"/(m|sp|i)/.*?$");
口頭で話したけんですけど、自分でも指摘してた通り、これがここにあるのはまずそうですね。

FzdbにHttpModuleを作って、そこで、DeviceTableを生成してCurrentに突っ込むのがいいかも。あと、リクエストされたURLがなんのデバイスか判断するのは正規表現を使うのは勿体無いですね。


```c#
private void Application_BeginRequest(object source, EventArgs a)
{
   var currentPageDevice = DeletectUrlDevice(Request.Url);
   //GetSettingPathはFzdbに実装。全エリア共通でOKだと思うのでプロジェクトディレクトリとかアプリケーションルートの相対パスから取れないかね？
   var settingPath = GetSettingPath();
   Sdx.Web.DeviceTable.Current  =  new Sdx.Web.DeviceTable(currentPageDevice, Request.Url, settingPath);
  
  var currentUserAgentDevice = DeletectUrlDevice();
  if(currentPageDevice == currentUserAgentDevice)
  {
     return;
  }
  
  //GetUrlが呼ばれて初めてsettingを読み込んで、pageの解析を行う。
  //結果はメモリにキャッシュしてください。
  var url =  Sdx.Web.DeviceTable.Current.GetUrl(currentUserAgentDevice);
  if(url != null)
  {
    Redirect(url);
  }
}
```

Currentを遅延生成（呼ばれた時に生成）できないとなると、下記のような実装がまずかった感じですかね。
```c#
foreach(var pageYaml in yamlSettings)
{
  var deviceTable = new Sdx.Web.DeviceTable(pageYaml);
  if(deviceTable.IsMatch(Device.Pc, HttpContext.Current.Request.Url))
  {
     return deviceTable;
  }
}
```

あくまで、一つだけ生成して、メソッドの中でマッチするか調べるのがよさそう。私が空で思いついたコードがまずかった。ごめん。やっぱ実装して見ないとわからないもんですね。

今のやり方のまま、デバイスを判別する部分だけ強引に外に出すこともできないことはないけど（例えばstaticな変数にメソッドを代入しておくとか・・・）、後々を考えるとこれがいいかな。実装に時間かかったのはIsMatchメソッドだと思うのでこういうふうに変えるのそんなに大変じゃないイメージがあるんだけど大変かな？w

HttpModule自体はSdxでもいいけど`DeletectUrlDevice`このメソッドを抽象メソッドにしておいて、Fzdbで実装するのがいいかもね。

😇

2016-12-05 07:02 UTC, gomo commented on Sdx/Web/DeviceTable.cs
> +      }
これ、コード見てて思ったけど、FzdbにModule作るならconfigから設定読まなくても良さそうですね。各サイトで同じところに置いてもらえばいいので。生成部分を見直しは、DeviceTableの方のコードに生成部分のイメージコードを書いておくので参考にしてください。

😇

2016-12-12 06:32 UTC, gomo requested changes

2016-12-12 06:32 UTC, gomo commented on Sdx/Web/DeviceTable.cs
> +    public void loadSettings(YamlSequenceNode yamlSettings)
こいつは公開する必要があるんでしたっけ？
😇

2016-12-12 06:32 UTC, gomo commented on UnitTest/Sdx/Web/DeviceTable.cs
> +    private void loadTestYaml(string filePath)
細かいですけど、このメソッドはつかってないかな？必要ないならみた人が迷うと思うので削除しちゃってください。ついでに、コメントアウトも削除しちゃってOKかな？

😇

2016-12-12 06:32 UTC, gomo commented on Sdx/Web/DeviceTable.cs
> +    public bool IsMatch(Device device, YamlMappingNode items)
こいつも公開する必要なさそう。インターフェースが変わって、変更忘れかな？確認お願いします。

😇

2016-12-12 06:32 UTC, gomo commented on Sdx/Web/DeviceTable.cs
> +    }
ここの処理の流れがうまく読み取れなかったので、明日口頭で説明してください。
😇

2016-12-12 06:32 UTC, gomo commented on Sdx/Web/DeviceRedirectHttpModule.cs
> +    public abstract Sdx.Web.DeviceTable.Device DetectUrlDevice(string url);
これもprotectedでOKかな？

😇

2016-12-12 06:32 UTC, gomo commented on Sdx/Web/DeviceRedirectHttpModule.cs
> +    public Sdx.Web.DeviceTable.Device DetectUserAgentDevice()
あ、こっちもかな？privateいける？

インターフェース変わって変更忘れもあるかもしれないけど、基本一番狭いので設定して、どうしても必要な時だけpublicにしていく流れで考えた方がいいです。C#はinternal( protected)というのもあるので忘れずに検討してください。

😇

2016-12-12 06:32 UTC, gomo commented on Sdx/Web/DeviceTable.md
>  deviceTable.GetUrl(Device.Sp);
この前見逃したけど、

```
 返ってくるパスは
 /tokyo/shop?tg_high=1&button=on
 です。
```
じゃなくて`/sp/tokyo/shop?tg_high=1&button=on`じゃない？

あと、よくこの手のコメントは

```
deviceTable.GetUrl(Device.Sp); // -> /sp/tokyo/shop?tg_high=1&button=on
```

とかソースコード内に書いたりします。

😇

2016-12-13 02:25 UTC, gomo requested changes
変数名とメソッド名の提案を投げました。全くこの通りにしなくてもいいけど参考にしてください。もっと分かりやすそうなのあったらお任せします。

2016-12-13 02:25 UTC, gomo commented on Sdx/Web/DeviceTable.cs
> +        loadSettings(yamlSettings);
口頭で話した件です。

ロード自体はコンストラクタで行なっていて、このメソッドは自分がどの設定にマッチするかを調べるメソッドなので名前が微妙ですね。

あと`settings.Count == 0`だとキャッシュ漏れが発生する可能性があるので、NULLにしておいて、一回目のチェックでnewした方が堅牢なコードと言えます。

```c#
if(currentPage == null) //currentPageがキャッシュ
{
  currentPage = DetectPage(currentUrl)
}
```

こんな感じのコードがいいかも。

2016-12-13 02:25 UTC, gomo commented on Sdx/Web/DeviceTable.cs
> +    private Dictionary<string, object> settings = new Dictionary<string, object>();
これは`currentPage`の方がいいかな。あと右側はYamlNode的な抽象クラスの方が意図がはっきりするかも。

😇

2016-12-13 02:25 UTC, gomo commented on Sdx/Web/DeviceTable.cs
> +    private YamlMappingNode currentDeviceQuery = new YamlMappingNode();
このキャッシュはcurrentPageに保持していそうなので必要なさそう。問題なければ削除お願いします。

😇

2016-12-13 02:25 UTC, gomo commented on Sdx/Web/DeviceTable.cs
> +    private string CurrentUrl { get; set; }
これはprivateだしプロパティーじゃなくてもいいかな。
`private string currentUrl`

😇

2016-12-13 04:09 UTC, shimizu-k-digi commented on Sdx/Web/DeviceRedirectHttpModule.cs
> +    public Sdx.Web.DeviceTable.Device DetectUserAgentDevice()
> 基本一番狭いので設定して、どうしても必要な時だけpublicにしていく流れで考えた方がいいです。C#はinternal( protected)というのもあるので忘れずに検討してください。

他のも含めて、変え忘れです。
次回以降は上記の考え方を忘れず実装します。

2016-12-14 06:37 UTC, gomo requested changes

2016-12-14 06:37 UTC, gomo commented on Sdx/Web/DeviceTable.cs
> +            if (match.Success)
口頭で話した件です。

ここのIF分いらないかも。二度同じ正規表現が評価されているので削除お願いします。
😇

2016-12-14 06:37 UTC, gomo commented on Sdx/Web/DeviceTable.cs
> +            string pattern = @"{([a-zA-Z0-9]+):(.*)}";
正規表現の実装を知らないのでなんとも言えないけど`{([a-zA-Z0-9]+):([^}]*)}`の方が安全というか、処理がかるそうな感じがした・・・

根拠が薄いのでなんですけど、触るついでに直してもらおうかな。
😇

2016-12-14 06:37 UTC, gomo commented on Sdx/Web/DeviceTable.cs
> +            string pattern = @"{([a-zA-Z0-9]+):(.*)}";
ここはそもそも正規表現を使わなくてもいけるんじゃないか？という話もあったので、それも確認して見てください。

😇

2016-12-15 02:35 UTC, gomo commented on Sdx/Web/DeviceTable.cs
> +            url = string.Join("/", split);
```c#
url.Split('/')
  .Select(val => val.IndexOf("{" + word.Key + ":") >= 0 ? word.Value : val)
  .Aggregate((current, next) => current + "/" + next);
```

2016-12-15 02:40 UTC, shimizu-k-digi commented on Sdx/Web/DeviceTable.cs
> +            url = string.Join("/", split);
ありがとうございます！
こっちの方がスマートなので変更します！

### 自分用のメモ
Aggregateの使い方
http://qiita.com/u_n_i_r_u_n/items/38a3545071c31bd00c5c

2016-12-16 02:32 UTC, gomo commented
👍

2016-12-28 01:28 UTC, shimizu-k-digi commented
### 追加作業
- [ ] 対応表に除外するクエリが設定されていたら、そのクエリは返すURLにつけない。

2016-12-29 02:15 UTC, gomo requested changes
ちょっと細かい修正と、テストの修正をお願いします。

2016-12-29 02:15 UTC, gomo commented on Sdx/Web/DeviceTable.cs
> +        }
細かいですけど、`query_match`と`perfect_match`が対応してないように感じました。おそらく、政策の作業進んでるのでそちらに影響ないように考えたのだと思いますが、`query_match_perfect`でどうでしょうか？

Fzdbとかだったら直すほどでもないですけど、Sdxなんでお願いします。

😇

2016-12-29 02:15 UTC, gomo commented on Sdx/Web/DeviceTable.cs
>              foreach (var item in pageYaml)
ここが、何をしてるのかピンとこなかったのでコメントを書いておいてもらえますか？
「YamlNodeのままだとキーへのアクセスが冗長なのでpageYamlをDictionaryに変換する」
とかですかね？

なんとなく、全ページを突っ込んでるように見えて、？？？となりました。

お願いします。

😇

2016-12-29 02:15 UTC, gomo commented on Sdx/Web/DeviceTable.cs
>              foreach (var item in pageYaml)
> 「YamlNodeのままだとキーへのアクセスが冗長なのでpageYamlをDictionaryに変換する」

こちらですけど、IsMatchの110行目にも書いておいてください。

😇

2016-12-29 02:15 UTC, gomo commented on UnitTest/Sdx/Web/DeviceTable.cs
>      }
excludeをテスト用のYamlに追加してるっぽいですけど、テストは書いてあるかな？一応確認お願いします。

テストを細かく分けちゃって、それぞれ、メソッド名になんのテストだかわかるようにしちゃったほうが後々良さそうですね。ついでにお願いします。

😇

2017-01-05 03:00 UTC, gomo commented
👍

2017-01-06 01:40 UTC, shimizu-k-digi commented
現在の仕様は
> query_matchは対象のクエリーを値まで一致で検索したい場合に記述します。
省略されたクエリーは検索対象にはならず、あってもなくてもマッチします
https://github.com/SunriseDigital/cs-sdx/blob/proj/deviceTable/Sdx/Web/DeviceTable.md

という仕様のため、例えば`/foo/bar/`や`/foo/bar?page=0`は別デバイスのURLが欲しいが、`/foo/bar?page=1`は別デバイスのURLがいらない（空で返ってきてほしいとき）場合にyamlに書きようがなく、対応できていないっぽい。

### 追記
解決方法について相談した結果`query_match_perfect`の中身が空だった場合、URLにクエリーがついていたらマッチさせないようにする。

2017-01-06 06:08 UTC, gomo requested changes

2017-01-06 06:08 UTC, gomo commented on UnitTest/Sdx/Web/DeviceTable.cs
> +      Assert.Equal("/m/yoshiwara/shop/", deviceTable.GetUrl(Sdx.Web.DeviceTable.Device.Mb));
これは、マッチしないテストを追加したほうがいいかな。

`var deviceTable = new Sdx.Web.DeviceTable(Sdx.Web.DeviceTable.Device.Pc, "/yoshiwara/shop/?foo=bar",...`

😇

2017-01-06 06:08 UTC, gomo commented on Sdx/Web/DeviceTable.cs
> +      if (splitUrl.Length <= 1)
直さなくていいですけど、このコードが何をしてるのか、上の方に遡ってやっとわかりました。とはいえわかりやすく書くの難しいですね。

PHPだったら
```php
list($path, $query) = explode("?", $url);

...
if(!$query)
{

}
```

と書くのがわかりやすいですけど、C#にlistはないので。

```c#
var splitUrl = currentUrl.Split('?');

var paths = splitUrl[0].Split('/');
var query = splitUrl[1];
```
しかないかなあ。いまいちだね。

あるいは、

```c#
var url = new Sdx.Web.Url(currentUrl);
```

を使ってしまうか・・・今更ですけど、最初に内部でこれ作っちゃって、こいつでゴニョゴニョするのも手でしたね。

2017-01-10 03:44 UTC, shimizu-k-digi commented
### キャッシュ機能を実装
対応表の量が多いときようにURLベースでのキャッシュを実装する。
現在のURLをテキストベースでキャッシュされているか見て、キャッシュされていたらそこからURLを返す。

2017-01-11 04:13 UTC, gomo commented
テスト確認しました。
👍 

キャッシュも一応確認しますかね。

2017-01-11 04:13 UTC, gomo approved these changes

2017-01-12 04:18 UTC, shimizu-k-digi commented
### 結構はまったのでメモ
MemoryCacheのコンストラクタにカスタムのキャッシュ名を引数で渡しても、キャッシュができない事象にはまった。

Defaultではないキャッシュ名をつける場合は、下記のような感じでConfigに使用するキャッシュの設定を書いておかないといけない。
``` xml
  <system.runtime.caching>
    <memoryCache>
      <namedCaches>
        <add name="DeviceTable"
                cacheMemoryLimitMegabytes="10"
                physicalMemoryLimitPercentage="60"
                pollingInterval="00:02:00" />
      </namedCaches>
    </memoryCache>
  </system.runtime.caching>
```

>  MemoryCache provides a constructor. We need to provide the name of cache configuration to use to construct the cache instance as follows:
http://www.shujaat.net/2011/03/wpf-configuring-systemruntimecachingmem.html

2017-01-18 05:09 UTC, gomo requested changes

2017-01-18 05:09 UTC, gomo commented on Sdx/Web/DeviceTable.cs
> +    private MemoryCache memoryCache = MemoryCache.Default;
Defaultを使うのは違和感があります。今回の用途では容量指定してしまうので、目的が限定されている様に感じます。というか、それぞれ目的に応じて、いろいろな設定をしそうですよね。キャッシュって。

なので、今回は外からインスタンスを足して、生成側でstaticな変数にしまって、渡す様にしましょう。外から渡す仕様にしておいたほうがSdx的に使い勝手もよさそうですし。

キャッシュはプロパティで保持して、もしNULLだったらキャッシュはしない方向でお願いします。チェック箇所見た感じそんなに大変じゃないですよね？たぶん。

😇

2017-01-20 06:41 UTC, gomo approved these changes
👍

2017-01-24 02:34 UTC, gomo requested changes

2017-01-24 02:34 UTC, gomo commented on Sdx/Web/DeviceRedirectHttpModule.cs
> +    }
口頭で話しましたけど、これはこういう話ではないですね。テンプレートメソッドパターンを使って、という話です。

目的は「継承した子クラスで別々のキャッシュ設定を使いたい」ということです。一つのタプリケーションでこのクラスを継承した複数のクラスを使うシチュエーションはあまりないかもしれませんが、何がるかわからないので、意味的にそのように設計したほうが正しいですね。

ただ、私の勘違いがあって、HttpModuleはリクエストごとに作られるらしいので、どこか別途staticな変数に入れないとダメっぽいですね。ということは、親クラスにstaticな変数を持ってしまうと全ての子クラスで共有されちゃうので、当初の目的を果たせないということになってしまいますね。

ということは最初に清水くんが実装した
https://github.com/SunriseDigital/cs-sdx/commit/3f33949d856aed84acb57a01a66eac400d6c2e6a#diff-0e2af672c7fd384142b3d25c2d309e0e
じゃないとダメってことになるのかな。ごめんね。

https://github.com/SunriseDigital/cs-sdx/blob/3f33949d856aed84acb57a01a66eac400d6c2e6a/Sdx/Web/DeviceRedirectHttpModule.cs#L76
一個前に戻って、このメソッドにコメント書いておいてもらえますか？

> HttpModuleはリクエストごとに生成されるのでMemoryCacheのインスタンスは必ずstaticな変数に保持してください。親クラスでは保持しません。キャッシュが必要ない場合はnullを返してください。

😇

2017-01-25 04:37 UTC, gomo approved these changes

2017-01-31 01:15 UTC, merged